### PR TITLE
Add Slovenian translation, fix small typo in German translation

### PR DESCRIPTION
**Pull request by anzepintar**
I added Slovenian translation. (forgot to commit everything in first PR)

### CODE REVIEW

**Comment by wedesoft** [comment]
You also need to add `anymeal/locale/sl/Makefile` to the outputs at the end of the `configure.ac` file. Let me know if you want me to do it.

**Comment by wedesoft** [comment]
Thanks btw :)

**Comment by anzepintar** [comment]
> You also need to add `anymeal/locale/sl/Makefile` to the outputs at the end of the `configure.ac` file. Let me know if you want me to do it.

fixed

**Comment by wedesoft** [comment]
Thanks for your contribution :)

**Comment by wedesoft** [comment]
I also added the Slovenian translation to the NSIS script for the Windows installer/uninstaller.

**Pull request merged**
