### PR TITLE
Update to Qt6

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
Addresses https://github.com/wedesoft/anymeal/issues/66
Initial review would be helpful

**Comment by bkmgit** [comment]
There is a bug that prevents builds on Ubuntu 22.04 without unusual modifications https://bugs.launchpad.net/ubuntu/+source/qtchooser/+bug/1964763

**Comment by wedesoft** [comment]
Looks good. Please add the link to Fedora instead of replacing the link to Arch. It is failing the GitHub Workflow builds. Maybe there is an image for ubuntu-24.04? Will have a look when I get the time.

**Comment by bkmgit** [comment]
There are two links for Arch
- [Arch Linux](https://aur.archlinux.org/packages/anymeal/)
- [Archlinux user repository page](https://aur.archlinux.org/packages/anymeal/)
which both point to the same location. Are they both needed?

**Comment by bkmgit** [comment]
Fedora build works. Ubuntu and Windows need updating. Build on Ubuntu 24.04 also needs an update.

**Comment by wedesoft** [comment]
Ah ok, if the Arch link was duplicate then it is fine to remove. Sorry

**Comment by wedesoft** [comment]
Maybe you can use pkgconfig (PKG_CHECK_MODULES) to find the Qt6 libraries. I haven't checked whether the Windows MinGW packages have pkgconfig files though. I haven't figured out yet how uic, rcc, and qtchooser works.

**Comment by bkmgit** [comment]
Ubuntu build now works, Will need to re-enable caching. It may be better to switch to CMake rather than using pkgconfig, but this is probably best done after the update to Qt6.

**Comment by wedesoft** [comment]
It fails on my machine because /usr/bin/moc generates code for Qt5. Not sure how this works. /usr/bin/moc is a symlink to qtchooser on my machine.

**Comment by bkmgit** [comment]
If both Qt5 and Qt6 are installed, may need to ensure moc-qt6 is picked up.   There is an example configuration for gpgme at https://github.com/msys2/MINGW-packages/blob/e858872a3b4d7ee9bfdc40f41aaead2bfc519186/mingw-w64-gpgme/0001-fix-find-moc-qt6.patch#L6

**Comment by wedesoft** [comment]
Ok, it compiled successfully. However the SVG icons are not showing at the moment.

**Comment by wedesoft** [comment]
Ok, I had to install libqt6svg6

**Comment by bkmgit** [comment]
Thanks. Still looking for QT_MOC and QT_UIC on Windows.

**Comment by bkmgit** [comment]
@wedesoft Are you able to test on Windows?

**Comment by wedesoft** [comment]
> @wedesoft Are you able to test on Windows?

Hi.
Yes, I have Windows 11 and Debian 12 here.

**Comment by bkmgit** [comment]
- Advice to follow https://github.com/gnu-octave/octave/blob/e3fc1567a0fe4921d678042e4d618bdf20ba2782/m4/acinclude.m4#L2133-L2179 to find libraries
- At the moment it fails on nsis step with `File: "C:\msys64\mingw64\share\qt6\plugins\printsupport\windowsprintersupport.dll" -> no files found.`

**Comment by wedesoft** [comment]
Hi, can you merge https://github.com/bkmgit/anymeal/pull/2 into your branch? It contains several fixes.

**Comment by wedesoft** [comment]
> * Advice to follow https://github.com/gnu-octave/octave/blob/e3fc1567a0fe4921d678042e4d618bdf20ba2782/m4/acinclude.m4#L2133-L2179 to find libraries
> 
>     * At the moment it fails on nsis step with `File: "C:\msys64\mingw64\share\qt6\plugins\printsupport\windowsprintersupport.dll" -> no files found.`

I couldn't find windowsprintersupport.dll for Qt6 on my system. Maybe that DLL is not needed any more?

**Comment by wedesoft** [comment]
> > * Advice to follow https://github.com/gnu-octave/octave/blob/e3fc1567a0fe4921d678042e4d618bdf20ba2782/m4/acinclude.m4#L2133-L2179 to find libraries
> >   
> >   * At the moment it fails on nsis step with `File: "C:\msys64\mingw64\share\qt6\plugins\printsupport\windowsprintersupport.dll" -> no files found.`
> 
> I couldn't find windowsprintersupport.dll for Qt6 on my system. Maybe that DLL is not needed any more?

Ok, there is ./msys64/mingw64/bin/Qt6PrintSupport.dll . Maybe need to package that instead.

**Comment by bkmgit** [comment]
> I couldn't find windowsprintersupport.dll for Qt6 on my system. Maybe that DLL is not needed any more?

qwindowsvista.dll and  windowsprintersupport.dll seem not to be in the core packages. qwindowsvista.dll is mentioned in the documentation https://doc.qt.io/qt-6/windows-deployment.html#qt-plugins but not sure if it is still needed. Maybe check if Windows build runs ok?

**Comment by wedesoft** [comment]
Looks like it built. Congrats!

**Comment by bkmgit** [comment]
Will address further feedback in the next day or so. Once ok, can clean up commit history.

**Comment by wedesoft** [comment]
According to https://packages.msys2.org/packages/mingw-w64-x86_64-qt6-base qmodernwindowsstyle.dll should exist. Strange.

**Comment by wedesoft** [comment]
Will try `pacman -Fy` and `pacman -Fx filename` when I find the time.

**Comment by bkmgit** [comment]
> According to https://packages.msys2.org/packages/mingw-w64-x86_64-qt6-base qmodernwindowsstyle.dll should exist. Strange.

qmodernwindowsstyle.dll does exist.  I have not been able to find qwindowsvistastyle.dll and windowsprintersupport.dll but do not know if they are still needed for correct functioning of the Anymeal on Windows.

**Comment by wedesoft** [comment]
Ok, windowsprintersupport.dll is not in any qt6 package according to pacman.

**Comment by wedesoft** [comment]
Tried the installer and libb2-1.dll was missing.

**Comment by wedesoft** [comment]
Printing works, but the GUI style is not like it used to be any more.

**Comment by wedesoft** [comment]
Looks like mingw-w64-x86_64-qt6-base version 6.7.2-2 has qmodernwindowsstyle.dll but not version 6.6.0-2 (which is installed on my machine). Have to figure out how to update things.

**Comment by wedesoft** [comment]
Hi, can you pull in https://github.com/bkmgit/anymeal/pull/3 ?

**Comment by wedesoft** [comment]
Hi, can you merge https://github.com/bkmgit/anymeal/pull/4 ? I think then it is ready to merge.

**Pull request merged**
